language: node_js
node_js: "6"
python: "2.7"

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set loglevel warn
  - npm install -g grunt-cli
  - export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
  - export CHROME_BIN=`which google-chrome` && $CHROME_BIN --version;
  - git clone --depth=50 --branch=master https://github.com/MarkLark/tuxt-server.git tuxt-server

install:
  - npm install
  - python --version
  - cd tuxt-server
  - pip install --user -q urllib3[secure]
  - pip install --user -q Flask==0.12
  - pip install --user -q -r requirements.txt
  - cd ..

script:
  - cd tuxt-server
  - python run-test-api.py &
  - cd ..
  - sleep 5s
  - grunt ci:travis
  - cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - grunt build
