language: node_js
node_js: "6"

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_install:
  - npm config set loglevel warn
  - npm install -g grunt-cli
  - export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
  - export CHROME_BIN=`which google-chrome` && $CHROME_BIN --version ;

install:
  - npm install

script:
  - grunt ci:travis
  - grunt build
