import 'app.scss';
import 'vendor';
import 'templates-cache.generated';

/* globals __TUXT_CONFIG__: true */
const appConfig = __TUXT_CONFIG__;

// alias for file generated by ngtemplates:gen-apps
import externalApps from 'external-apps';

let body = angular.element('body');

body.ready(() => {
    // update config via config.js
    if (window.tuxtConfig) {
        angular.merge(appConfig, window.tuxtConfig);
    }

    // non-mock app configuration must live here to allow tests to override
    // since tests do not import this file
    angular.module('tuxt.config').constant('config', appConfig);

    angular.bootstrap(body, [
        'tuxt.config',
    ].concat(externalApps), {strictDi: true});

    window.dstoreIsReady = true;
});